mods:
  - screepsmod-auth
  - screepsmod-admin-utils
  - screepsmod-mongo

launcherOptions:
  autoUpdate: false
  logConsole: true

serverConfig:
  shardName: autoscreeps
  socketUpdateRate: 250
  welcomeText: |
    <h1>autoscreeps</h1>
    <div>Local experimental Screeps server</div>
